stages:
- name: install
  steps:
  - runScriptConfig:
      image: cloud-native-hbr.ad.infosys.com/rancher/node:latest
      shellScript: |-
        npm set registry http://infynp.ad.infosys.com/repository/npm-group/
        npm install
    envFrom:
    - sourceName: harbor-registry
      sourceKey: username
      targetKey: username
    - sourceName: harbor-registry
      sourceKey: password
      targetKey: password
- name: code formatting
  steps:
  - runScriptConfig:
      image: cloud-native-hbr.ad.infosys.com/rancher/node:latest
      shellScript: npm run format
  - runScriptConfig:
      image: cloud-native-hbr.ad.infosys.com/rancher/node:latest
      shellScript: npm run build
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: snehil.srivastava01/app:v1
      pushRemote: true
      registry: infydtr.ad.infosys.com
    env:
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
