stages:
- name: install
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm install
    envFrom:
    - sourceName: harbor-registry
      sourceKey: username
      targetKey: username
    - sourceName: harbor-registry
      sourceKey: password
      targetKey: password
- name: code formatting
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm run format
  - runScriptConfig:
      image: node:latest
      shellScript: npm run build
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: nickngch90/node-web-app
      pushRemote: true
      registry: harbor.nick.support.rancher.space
    env:
      PLUGIN_INSECURE: "true"
timeout: 60
notification: {}
