stages:
- name: install
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm install
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: nickngch90/node-web-app
      pushRemote: true
      registry: harbor.nick.support.rancher.space
    env:
      PLUGIN_INSECURE: "true"
timeout: 60
notification: {}
