stages:
- name: install
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm install
    envFrom:
    - sourceName: p-bqqls-harbornicksupportrancherspace
      sourceKey: username
      targetKey: username
    - sourceName: p-bqqls-harbornicksupportrancherspace
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: nickngch90/node-web-app
      pushRemote: true
      registry: docker.nick.support.rancher.space
    env:
      PLUGIN_INSECURE: "true"
timeout: 60
notification: {}
