stages:
- name: install
  steps:
  - runScriptConfig:
      image: harbor.nick.support.rancher.space/nickngch90:latest
      shellScript: npm install
    envFrom:
    - sourceName: p-2nssb-dockernicksupportrancherspace
      sourceKey: username
      targetKey: username
    - sourceName: p-2nssb-dockernicksupportrancherspace
      sourceKey: password
      targetKey: password
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: nickngch90/node-web-app
      pushRemote: true
      registry: docker.nick.support.rancher.space
    env:
      PLUGIN_INSECURE: "true"
timeout: 60
notification: {}
